### ISSUE TITLE
readFile method error

### ISSUE THREAD

**Issue by dahuahe** [sanketbajoria/ssh2-promise#1]
![image](https://user-images.githubusercontent.com/16739083/34352868-fc942fca-ea5f-11e7-9e97-19a748f4ebb1.png)
![image](https://user-images.githubusercontent.com/16739083/34352877-04c30202-ea60-11e7-8988-aae9ce02e872.png)

**Comment by sanketbajoria** [comment]
Seems, like, i have implemented the wrapper for readFile and writeFile, in wrong manner. I have corrected it. Please take a new version 0.0.8

**Comment by sanketbajoria** [comment]
Fixed. Closing this issue
