### ISSUE TITLE
TypeScript: SSHConnections Missing Properties

### ISSUE THREAD

**Issue by 3DEsprit** [sanketbajoria/ssh2-promise#12]
Version: 0.1.1

I was checking this library out for a TS project, and noticed the ssh.shell method prop could not be found:

<img width="547" alt="screen shot 2018-10-21 at 20 41 25" src="https://user-images.githubusercontent.com/3156278/47275116-27788d00-d572-11e8-83fb-0c508f30eac5.png">

By the way, this happens with both ssh.exec, and ssh.shell (naturally). 

While I'm very use to JS, I'm not too use to TS so this could be user error, in which I apologize.

I did manually reference the sshConnections.d file, to which nothing changed leading me to believe the above was correct. While it may not be needed, I do have the @types/ssh2 installed. 

I'm curious, is there a reason the type defs aren't being run through DefinitelyTyped? It seems everything else works regardless, but I guess to me it's nice to know where they are and if there is anything I need to add to the compiler types. Is there a possibility of adding a note about this in the README?

Anyways, thanks for this library! It looks great so far. 👍

**Comment by martindandanell** [comment]
If you init `SSH2Promise.SSH` instead of `SSH2Promise` directly, it will give you an instance of the `SSHConnection` object in which the `exec` and `shell` functions exists - at least this worked for me.

**Comment by sanketbajoria** [comment]
@3DEsprit , ah, i can see typescript property is missing. I am fixing this up. Will be fixed by next release

@martindandanell  Actually, if we use in above manner, then it won't be providing the feature of connection hopping, which this library intend to do.

**Comment by 3DEsprit** [comment]
Thanks @sanketbajoria !

**Comment by 3DEsprit** [comment]
It looks like there are a few other missing type definitions here, like shell, spawn, getSocksPort, addTunnel, getTunnel, x11, and subsys. Adding each method's signature definition to the index.d.ts has at least allowed me to use each without much issue.

Also, it seems the current signature for the shell method in sshConnections is set with mandatory options, instead of the optional options parameter setup referenced in the docs. Did this change?

**Comment by sanketbajoria** [comment]
@3DEsprit 
Fixed this issue, now, it should provide typescript support for all missing type definition.

**Comment by 3DEsprit** [comment]
I'm guessing you already know, but doesn't look like the change was applied. I'm not seeing the update in the repo, or the npm package yet.

**Comment by sanketbajoria** [comment]
@3DEsprit 
Yes, i have created a patch on a separate branch. Haven't pushed it yet on master branch or npm repository.
Can you please test it at your end, by just specifying github ssh2-promise branch entry in package.json file. Once, you confirm it, i will push the changes

**Comment by 3DEsprit** [comment]
Looks good! It looks like Shell is requiring the options, instead of being optional.

**Comment by sanketbajoria** [comment]
Ah, good catch.. fixed it.

**Comment by 3DEsprit** [comment]
Looking good on this end. Thanks! 👍

**Comment by sanketbajoria** [comment]
Published to master repository and npm repository
Thanks

**Comment by 3DEsprit** [comment]
Any time! Closing.
