### ISSUE TITLE
Get the return code of an execution of a script

### ISSUE THREAD

**Issue by benjaminpech** [sanketbajoria/ssh2-promise#17]
Hi, 

I'm trying to get the return code of a _exec_ from a bash script on my server.
It would be nice to have in output, both stderr and stdout to detect technical issues and the return code (eg. 0 or 1).

It's possible to do that ?

**Comment by sanketbajoria** [comment]
Currently, it return either stdout (resolve) or stderr (reject) in promisify manner . Below is current implementation

![image](https://user-images.githubusercontent.com/2969587/47807196-80f66e00-dd61-11e8-884a-b93cbff018ad.png)

Getting a return code would be difficult, but you can get the error message to detect the technical issue

**Comment by sanketbajoria** [comment]
as no update, hence closing this bug. 
Please feel free to reopen this bug, if feel otherwise
