### ISSUE TITLE
Nested tunnel connection will need "sock" instead of "host" configuration.

### ISSUE THREAD

**Issue by lianghwajou** [sanketbajoria/ssh2-promise#19]
Will need to use {sock: stream} instead of {host: host} in ssh configuration in order to build a nested tunnel.

ssh2-promise@0.1.2
sshConnections.js

   connect(c) {^M
        this.config = Object.assign(this.config, c);^M
        ++this.__retries;^M
        if (this.__$connectPromise != null)^M
            return this.__$connectPromise;^M
        this.__$connectPromise = new Promise((resolve, reject) => {^M
            this.emit(sshConstants_1.default.CHANNEL.SSH, sshConstants_1.default.STATUS.BEFORECONNECT);^M
-            if (!this.config || typeof this.config === 'function' || !this.config.host || !this.config.username) 
{^M
+           if (!this.config || typeof this.config === 'function' || !(this.config.host || this.config.sock) || !this.config.username) 
{^M
                reject("Invalid SSH connection configuration host/username can't be empty");^M
                this.__$connectPromise = null;^M
                return;^M
            }^M

**Comment by sanketbajoria** [comment]
@lianghwajou 
Please, feel free to open PR for this.

**Comment by lianghwajou** [comment]
Submitted a pr https://github.com/sanketbajoria/ssh2-promise/pull/21

**Comment by sanketbajoria** [comment]
@lianghwajou 
Sorry didn't much time to review it. I will merge it, in next few days.

**Comment by sanketbajoria** [comment]
@lianghwajou 
Published new version, with your merge request. 👍
