### ISSUE TITLE
find Repeat call readFile error

### ISSUE THREAD

**Issue by dahuahe** [sanketbajoria/ssh2-promise#2]
when i  Repeat call readFile i find process be hanging [not continue ] only finish first readFile
then i read src find err and fix  but i think my fix is out of place..
fix picture 
![image](https://user-images.githubusercontent.com/16739083/34368259-610de634-eaed-11e7-9772-08701f0e59af.png)
$read has been change
so 
![image](https://user-images.githubusercontent.com/16739083/34368267-73ecfa10-eaed-11e7-8cc2-f52bf2509102.png)
3Q,

**Comment by sanketbajoria** [comment]
Seems like, no continue event is present for readFile and writeFile api. Please, take latest code from github, it should work fine now. I haven't published it to npm yet.

**Comment by sanketbajoria** [comment]
Closing this issue, as resolved
