### ISSUE TITLE
Switch socksv5 dependency

### ISSUE THREAD

**Issue by NetOperatorWibby** [sanketbajoria/ssh2-promise#20]
`socksv5` has a minor vulnerability via the `ipv6` module that has since been renamed to `ip-address`. Heroku has published a fork of `socksv5` that replaces the outdated `ipv6` with `ip-address`.

You can find [their fork here](https://github.com/heroku/socksv5).

**Comment by sanketbajoria** [comment]
@NetOperatorWibby 
Switched to heroku version
https://github.com/sanketbajoria/ssh2-promise/commit/240b3138e5d5663d7c66a4385e1c8bb01087483b
