### ISSUE TITLE
Typescript integration

### ISSUE THREAD

**Issue by jeffrson** [sanketbajoria/ssh2-promise#22]
Hi,
would love to see typescript support like
`import { SFTP } from 'ssh2-promise'`

Currently there seems to be no way to access the type of SFTP (in class or interface) at all.

**Comment by sanketbajoria** [comment]
Currently it is exposed as below
var SFTP = require('ssh2-promise').SFTP

**Comment by sanketbajoria** [comment]
import SFTP = require('ssh2-promise').SFTP

**Comment by jeffrson** [comment]
Then it's just "any".

**Comment by grammati** [comment]
Workaround:

```typescript
import Ssh from "ssh2-promise";
const dummy = () => new Ssh({}).sftp();
type SFTP = ReturnType<typeof dummy>;
```

**Comment by sanketbajoria** [comment]
Now we support SFTP type
```
//without esModuleInterop
import SFTP = require('ssh2-promise/lib/sftp')

//with esModuleInterop
import SFTP from 'ssh2-promise/lib/sftp'
```
