### ISSUE TITLE
Typescript error with createReadStream

### ISSUE THREAD

**Issue by jeffrson** [sanketbajoria/ssh2-promise#24]
This typescript source
```
import SSH2Promise = require('ssh2-promise')

let sshconfig = {}

let ssh = new SSH2Promise(sshconfig)
let sftp = ssh.sftp()

sftp.createReadStream('/file')
```

gives the following error (TS 3.3):

> error TS2554: Expected 0 arguments, but got 1.

for sftp.createReadStream.

**Comment by sanketbajoria** [comment]
Will be fixing it soon. Typescript index file wrongly generated.

**Comment by sanketbajoria** [comment]
@jeffrson 
Fixed it
https://github.com/sanketbajoria/ssh2-promise/commit/dad5e3f0028f6fe16e4bbf1b4aefaa005e7bf01c
