### ISSUE TITLE
`specs/fixture.json` file is missing

### ISSUE THREAD

**Issue by jlyonsmith** [sanketbajoria/ssh2-promise#29]
It is impossible to run the tests because there is no `fixture.json` file.  It seems that it should contain a bunch of types of configuration.  Presumably it was left out because there was passwords in there.  If you could commit an example it would make it easier to reproduce.  Plus then folks could actually test before submitting PR's!

**Comment by sanketbajoria** [comment]
@jlyonsmith 
Yes, you are right, i wasn't able to commit, because, it contains, actual server details. Let me commit few open server detail, which i can.

**Comment by jlyonsmith** [comment]
Thanks @sanketbajoria   I have a small PR that I would like to submit but I would like to ensure that I haven't broken anything!

**Comment by sanketbajoria** [comment]
@jlyonsmith 
Integrated Travis ci, so if you raise a pull request, it should run the test cases automatically.
For local testing, updated the Readme section.
