### ISSUE TITLE
How to stop a command?

### ISSUE THREAD

**Issue by fgheorghe** [sanketbajoria/ssh2-promise#3]
How do i stop a command, i.e.: tail:
//use spawn, if you want to stream on output of command
(async function(){
    var socket = await ssh.spawn("tail -f /var/log.txt");
    socket.on('data', () => {
      //file content will be available here
    })
})();

Basically, I would like to kill the tail command when terminating a connection.

Thank you

**Comment by nallown** [comment]
send a CTRL+C instruction to the socket. I'm not sure how to do that but you can just send a CTRL+C instruction to end it.

Also you can just close the socket connection. Maybe there's a `socket.close()` command.

**Comment by fgheorghe** [comment]
Thank you for your reply - sometimes when i close the socket, the command won't stop. Will try sending a CTRL+C instruction instead.

**Comment by nallown** [comment]
People are saying that `\x003` or `\x03` is a CTRL+C instruction btw.

**Comment by sanketbajoria** [comment]
Please pass {pty: true}  as second parameter when spawning a tail command. Before closing,  pass SIGKILL command via socket.

**Comment by fgheorghe** [comment]
Thank you all.

The following appears to have worked:
Setting the pty to true, as per @sanketbajoria suggestion.
Sending a \x03 before closing the connection.

Great community! Will close this "issue" now.
