### ISSUE TITLE
String identity

### ISSUE THREAD

**Issue by LeonAlvarez** [sanketbajoria/ssh2-promise#36]
Is there any way to use a string as identity instead of using path of the private key.

**Comment by sanketbajoria** [comment]
@LeonAlvarez 
pass configuration as below under privateKey
`
var sshconfig2 = {
  host: '192.168.1.3',
  username: 'ubuntu',
  privateKey: '<privateKey>'
}
`

**Comment by LeonAlvarez** [comment]
ty
