### ISSUE TITLE
Remove console.log statements from SSHConnection.spawn()

### ISSUE THREAD

**Issue by mwgamble** [sanketbajoria/ssh2-promise#37]
It would be really helpful if the `console.log()` statements in `SSHConnection.spawn()` could be removed. I'm trying to use this library in a CLI application, and every time a command finishes executing I get two "Closed stream" messages whether I like it or not.

**Comment by sanketbajoria** [comment]
@mwgamble 

Yes, sure, thanks for pointing it out.

**Comment by sanketbajoria** [comment]
Done
