### ISSUE TITLE
Why are dist files not .gitignored

### ISSUE THREAD

**Issue by cinderblock** [sanketbajoria/ssh2-promise#43]
Why are `dist` files not `.gitignore`d?

**Comment by sanketbajoria** [comment]
@cinderblock 
Actually i am publishing npm package through dist folder.

**Comment by cinderblock** [comment]
Yes, you should publish the dist folder on npm (and arguably *not* the src folder).

That doesn't explain why the `dist` folder is checked into the git repository. The general consensus is that generated files should not be in repositories.

**Comment by sanketbajoria** [comment]
@cinderblock 
Yes, i should publish npm package from dist folder. It will require to update the package.json.
Will do in next release

**Comment by cinderblock** [comment]
It **should** just take two things:
1. Add a `prepare` script that calls `tsc` (or `npm run build`)
2. Add an `.npmignore` file **or** add a `files` field to `package.json`

For more details about why these steps are needed/helpful, I'll post you to [my SO post](https://stackoverflow.com/questions/48287776/automatically-build-npm-module-on-install-from-github/57503862#57503862):
> ### Problems with `.gitignore`
> 
> There is one issue with this option that gets many people. When preparing a dependency, Npm and Yarn will **only** keep the files that are listed in the `files` section of `package.json`.
> 
> One might see that [`files` defaults to all files being included](https://docs.npmjs.com/files/package.json#files) and think they're done. What is easily missed is that `.npmignore` *mostly* overrides the `files` directive **and**, if `.npmignore` does not exist, `.gitignore` is used instead.
> 
> So, if you have your built files listed in `.gitignore` like a sane person, don't list your built files in `files`, and don't use a `.npmignore` file, **`prepare` will *seem* broken**.
> 
> If you fix `files` to only include the built files or add an empty `.npmignore`, you're all set.

**Comment by sanketbajoria** [comment]
Done
