### ISSUE TITLE
Connection Limit ?? 

### ISSUE THREAD

**Issue by waterfallm** [sanketbajoria/ssh2-promise#45]
I'm running ssh.exec in a loop firing 35 commands at the same server, i'm assuming ssh2-promise either reuses or disconnects before each ssh.exec call.

Is there some limit in ssh2-promise or the dependencies that limits to either 5 or 10 connections?

**Comment by sanketbajoria** [comment]
@waterfallm 
Currently there is no limit. We have to handle it manually.

**Comment by waterfallm** [comment]
I found the limit my servers had limit specified in the ufw config.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by waterfallm** [comment]
Yes the ufw config'd FW was limiting the connection attempts to 5 in 30 secs. Decided to work within those constraints and improve application logic.
