### ISSUE TITLE
ssh.exe does not resolve on Ubuntu 18.04 nodejs v8.10.0

### ISSUE THREAD

**Issue by goflatworld** [sanketbajoria/ssh2-promise#46]
Below code works. It returns the username. But it does not close the SSH session. I have to manually  stop it. I tried other Linux command. None of them resolve...

      `var SSH = require('ssh2-promise');

        var sshconfig = {
        host: 'x.x.x.x'
        username: 'yyyyy',
        privateKey: '-----BEGIN RSA PRIVATE KEY-----'};``
        var ssh= new SSH(sshconfig);
        (async function(){
            var data = await ssh.exec('whoami');
            console.log(data); //ubuntu
        })();`

**Comment by sanketbajoria** [comment]
Can you please add
```await ssh.close()```

It will close all connection
