### ISSUE TITLE
How to make 2 exec command in one connection

### ISSUE THREAD

**Issue by abdrozak20** [sanketbajoria/ssh2-promise#49]
I want to exec my command paralel

this is my code 
![image](https://user-images.githubusercontent.com/33420123/85915771-8082e300-b874-11ea-9494-1a364d326897.png)

and i hope the result like this
![image](https://user-images.githubusercontent.com/33420123/85915776-92fd1c80-b874-11ea-9f70-0b19dc55e714.png)

**Comment by sanketbajoria** [comment]
@abdrozak20  actually we want to execute anything in parallel... just use 
```
x.then(() => Promise.all(x.exec('cmd 1'), x.exec('cmd 2')))
```
