### ISSUE TITLE
Timed out while waiting for handshake

### ISSUE THREAD

**Issue by KwangGan** [sanketbajoria/ssh2-promise#51]
Hi, Thank for great library 

I used this as SFTP Client to ReadStreamfile to S3 for year but now I got an error 

"Timed out while waiting for handshake" 

If I use SSH2 package to connect same server it works but with this SSH2-promise it stall and timeout 

Could you please suggest :D

**Comment by sanketbajoria** [comment]
@KwangGan 
Can you please provide some code, how are you using it. (Config part and how you are streaming file.)

**Comment by kpeters-cbsi** [comment]
@KwangGan Are you trying to connect to SalesForce by any chance?

**Comment by kpeters-cbsi** [comment]
I'm experiencing a similar problem, but only when connecting to a particular host. I've attached the log from a recent run. Note that I'm using this inside of a Lambda function.

[log-events-viewer-result-2.zip](https://github.com/sanketbajoria/ssh2-promise/files/4968956/log-events-viewer-result-2.zip)

**Comment by KwangGan** [comment]
Thank you for reply 

My problem solved. 

I increase readyTimeout  from 5 seconds to 20 seconds and It works as expect
