### ISSUE TITLE
Do you have any plans to update the dependency package ssh2 to version 1.1?

### ISSUE THREAD

**Issue by noteon** [sanketbajoria/ssh2-promise#62]
SSH2 has released version 1.1, do you have any plans to synchronize the package dependencies?

**Comment by sanketbajoria** [comment]
@noteon Will release ssh2-promise based upon ssh2 1.1 by today

**Comment by sanketbajoria** [comment]
@noteon Upgraded ssh2-promise

**Comment by noteon** [comment]
Thanks, It works well.
