### ISSUE TITLE
X11 forwarding may fail if X server is listening on a Unix Socket

### ISSUE THREAD

**Issue by jeremyfix** [sanketbajoria/ssh2-promise#64]
Hello,

for `x11`, it might be that the X server is listening on a Unix socket and not a TCP port and host (see [the ssh2/issue#1053](https://github.com/mscdex/ssh2/issues/1053) ).

For that case to work, we need to connect to the X server with the socket, for example :
```
xserversock.connect('/tmp/.X11-unix/X0');
```

rather than 
```
xserversock.connect(6000, 'localhost');
```

which is actually the code used in  [src/sshConnection.ts#L265](https://github.com/sanketbajoria/ssh2-promise/blob/1aa2bfba3ae9d56e29040a8e98b01bef6544259a/src/sshConnection.ts#L265) which means the x11 call will fail if the X server is using a Unix socket. 

I do not know what is the best way to parametrize this, maybe by providing an option to the `SSH2Promise.x11` or an option of SSHConfig given to the constructor ? Actually , I do not know if it is possible to programatically determine if the X server is using a socket or a port and on which ones it is listening. 

Best.
Jeremy.

**Comment by sanketbajoria** [comment]
@jeremyfix 

To support this, I think, we have to support both, we have to change this sshConnection.ts#L254 to sshConnection.ts#L265. So that, if unix socket has been passed, then, create client as below
```js
var xserversock = net.createConnection("/tmp/mysocket");

xserversock.on("connect", function() {
                  var xclientsock = accept();
                  xclientsock.pipe(xserversock).pipe(xclientsock);
                  this.__x11.resolve();
                 this.emit(SSHConstants.CHANNEL.X11, SSHConstants.STATUS.CONNECT);
});

```

**Comment by sanketbajoria** [comment]
@jeremyfix please refer to this commit b8aebe5

Can you please confirm, if it fixes your problem.

**Comment by sanketbajoria** [comment]
@jeremyfix 
ssh2-promise@1.0.1 has been published.
I have introduced new attribute in sshConfig named x11 to solve your problem
![image](https://user-images.githubusercontent.com/2969587/131229559-d76268f4-af72-4e0e-beda-a8ad31a8bf90.png)

**Comment by jeremyfix** [comment]
Thank you for your help ;

Sorry for not being able to test, I finally moved to ssh2 directly in my [project](https://github.com/jeremyfix/dcejs) rather than using ssh2 promise. I then have to write my own promise but I had the feeling I would better learn to code directly with ssh2 rather than with an abstraction.

I close your issue. I think your commit did allow now to handle the case I was mentioning.
