### ISSUE TITLE
error when a tunnel connection fails

### ISSUE THREAD

**Issue by Slavrix** [sanketbajoria/ssh2-promise#7]
When a tunnel errors, an error is thrown that the name cant be found.

line 352 of sshConnections looks like its the culprit.

name should be changed to tunnelConfig.name

**Comment by sanketbajoria** [comment]
Thanks for pointing it out. Will be releasing fix soon.

**Comment by sanketbajoria** [comment]
Fixed. https://github.com/sanketbajoria/ssh2-promise/commit/f6c9f7f708ec329d2a313e8d90ca65b3beeb4cad
