### ISSUE TITLE
fastPut error

### ISSUE THREAD

**Issue by rahbari** [sanketbajoria/ssh2-promise#9]
I get this when usign fastPut:

```
node_modules\ssh2-streams\lib\sftp.js:1137
                    cb();
                    ^
TypeError: cb is not a function
    at \node_modules\ssh2-streams\lib\sftp.js:1137:21
    at \node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:139:20)
```

**Comment by sanketbajoria** [comment]
let me debug the issue. Can you please share the code snippet in meanwhile, so that i can see how you are using this function

**Comment by rahbari** [comment]
I used
`var sftp = await ssh.sftp();`
instead of
`var sftp = new SSH2Promise.SFTP(ssh);`
await ssh.sftp() in docs leads to confusion.

thank for awesome work btw.

**Comment by sanketbajoria** [comment]
Below is sample code, how should we use it. 
```
var ssh = new SSH2Promise(sshconfig);
var sftp = new SSH2Promise.SFTP(ssh);
await sftp.fastPut('C:\\test\\test1\\test2.log', "/home/ubuntu/test2.txt");
```
things are working as expected, please let me know, if you are still facing error

**Comment by rahbari** [comment]
I got it working, thank you so much.
